### ISSUE TITLE
Native & Turbo Module Development

### ISSUE THREAD

**Issue by lewatt23** [kleydon/rn-wav-to-flac#3]
Hello,
I will start by apologizing cause this is not really and issue but a call to help ^^!, So am trying to develop a native module (file content encryption) for react-native but am kinda of lost on how to go about it then i stumbled in your repo, which does something similar to what i want to achieve with my module, cause am trying to build a module that encode and decode pdf file contents. so i was wondering if you have a more detailed articles with examples just like yours or blog where i can find resources on how i can build a JSI module. (sorry once more ^^!)

**Comment by kleydon** [comment]
Hi @lewatt23 - just responded by email; hoping it helps!
